# Generated by Django 4.0.4 on 2022-07-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
