# Generated by Django 4.0.4 on 2022-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowling', '0002_alter_portal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='exNum',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='stat',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
